### ISSUE TITLE
Crawler is not working on server

### ISSUE THREAD

**Issue by hchangjae** [paywteam/eodiro#156]
**Describe the bug**
Crawler is not working on server. Because of performance

even aws server (cpu v2, 4gb mem ) has been broke down.

**Comment by jhaemin** [comment]
We should upgrade the server computer. 💸

**Comment by hchangjae** [comment]
I'm not sure upgraded server computer can solve this problem.
performance difference may not be big

**Comment by jhaemin** [comment]
Then what about finding a lighter alternative of puppeteer?

**Comment by jhaemin** [comment]
Resolved by upgrading the server.
